create_clock -period 100.000 -name clk -waveform {0.000 50.000} [get_ports clk]
set_input_delay -clock [get_clocks clk] -min -add_delay 2.000 [get_ports {data_i[*]}]
set_input_delay -clock [get_clocks clk] -max -add_delay 2.000 [get_ports {data_i[*]}]
set_input_delay -clock [get_clocks clk] -min -add_delay 2.000 [get_ports {key_i[*]}]
set_input_delay -clock [get_clocks clk] -max -add_delay 2.000 [get_ports {key_i[*]}]
set_input_delay -clock [get_clocks clk] -min -add_delay 2.000 [get_ports decrypt_i]
set_input_delay -clock [get_clocks clk] -max -add_delay 2.000 [get_ports decrypt_i]
set_input_delay -clock [get_clocks clk] -min -add_delay 2.000 [get_ports load_i]
set_input_delay -clock [get_clocks clk] -max -add_delay 2.000 [get_ports load_i]
set_input_delay -clock [get_clocks clk] -min -add_delay 2.000 [get_ports reset]
set_input_delay -clock [get_clocks clk] -max -add_delay 2.000 [get_ports reset]
set_output_delay -clock [get_clocks clk] -min -add_delay 0.000 [get_ports {data_o[*]}]
set_output_delay -clock [get_clocks clk] -max -add_delay 2.000 [get_ports {data_o[*]}]
set_output_delay -clock [get_clocks clk] -min -add_delay 0.000 [get_ports ready_o]
set_output_delay -clock [get_clocks clk] -max -add_delay 2.000 [get_ports ready_o]
