set_property SRC_FILE_INFO {cfile:/home/danman/sauce/vivado/OpenSesame/opensesame/opensesame.srcs/constrs_1/new/aes.xdc rfile:../../../opensesame.srcs/constrs_1/new/aes.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y9 [get_ports clk_0]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks clk_0] -to [get_clocks clk_fpga_0]
